### PR TITLE
Update list.csv

### PR DESCRIPTION
**Pull request by lmenard**
Hi, I would like to have the error on the web service-energy item in the gallery to be fixed. Thanks

### CODE REVIEW

**Comment by fxprunayre** [comment]
What is the error ? You dropped one ref and the other does not provide the URL of the catalog. Is this what you want ? or should we move the URL from the first reference to the last one ?

**Comment by fxprunayre** [comment]
Fixed applied as described in last comment.

**Comment by lmenard** [comment]
Hi Francois,
I would like to simply have e consistent item as others in the gallery list so from left to right:
[ICON] webservice-icon-texte-128.gif | [TITLE] Webservice-Energy | [URL] http://geocatalog.webservice-energy.org | [DESCRIPTION]  Webservice-Energy Catalog provides worldwide information about Renewable Energy and Environment.

As simple as it seems I cannot make it work… :-/

Thanks for your help.

Cheers,

Lionel
—————
Lionel MENARD, MINES ParisTech CS 10207 F-06904 Sophia Antipolis France Tel +33 493957423

**Comment by fxprunayre** [comment]
Done. We'll update the website shortly.

**Comment by lmenard** [comment]
Thanks you very much Francois…

Lionel
—————
Lionel MENARD, MINES ParisTech CS 10207 F-06904 Sophia Antipolis France Tel +33 493957423

**Pull request merged**
